services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    ports:
      - 1521:1521
    environment:
      - "ORACLE_PWD=password"
    volumes:
      - oracle-data:/opt/oracle/oradata


volumes:
  oracle-data: