package dummyGenderator

import kotlin.random.Random

data class Person(
    val name: String,
    val firstName: String,
    val postcode: String,
    val city: String,
    val country: String,
    val occupation: String
) {
    override fun toString(): String {
        return "('$name', '$firstName', '$postcode', '$city', '$country', '$occupation')"
    }
}

fun main() {
    val tableName: String = "PERSON_DATA_D"
    val values: Int = 10000

    val insertStatement: StringBuilder = StringBuilder();
    insertStatement.append("INSERT INTO $tableName (name,first_name, postcode, city, country, occupation) VALUES \n")
    for (i in 0..<values) {
        val person: Person =
            Person(
                names.random(),
                firstNames.random(),
                Random.nextInt(10000, 99999).toString(),
                cities.random(),
                countries.random(),
                occupations.random()
            )
        insertStatement.append(person)
        if (i < values-1) {
            insertStatement.append(",\n")
        }
    }
    insertStatement.append(";")
    println(insertStatement.toString())
}


// From https://de.wikipedia.org/wiki/Liste_der_h%C3%A4ufigsten_Familiennamen_in_Deutschland
val names: List<String> = listOf(
    "Müller",
    "Schmidt",
    "Schneider",
    "Fischer",
    "Weber",
    "Meyer",
    "Wagner",
    "Becker",
    "Schulz",
    "Hoffmann",
    "Schäfer",
    "Koch",
    "Bauer",
    "Richter",
    "Klein",
    "Wolf",
    "Schröder",
    "Neumann",
    "Schwarz",
    "Zimmermann",
    "Braun",
    "Krüger",
    "Hofmann",
    "Hartmann",
    "Lange",
    "Schmitt",
    "Werner",
    "Schmitz",
    "Krause",
    "Meier",
    "Lehmann",
    "Schmid",
    "Schulze",
    "Maier",
    "Köhler",
    "Herrmann",
    "König",
    "Walter",
    "Mayer",
    "Huber",
    "Kaiser",
    "Fuchs",
    "Peters",
    "Lang",
    "Scholz",
    "Möller",
    "Weiß",
    "Jung",
    "Hahn",
    "Schubert",
    "Vogel",
    "Friedrich",
    "Keller",
    "Günther",
    "Frank",
    "Berger",
    "Winkler",
    "Roth",
    "Beck",
    "Lorenz",
    "Baumann",
    "Franke",
    "Albrecht",
    "Schuster",
    "Simon",
    "Ludwig",
    "Böhm",
    "Winter",
    "Kraus",
    "Marin",
    "Schumacher",
    "Krämer",
    "Vogt",
    "Stein",
    "Jäger",
    "Otto",
    "Sommer",
    "Groß",
    "Seidel",
    "Heinrich",
    "Brandt",
    "Haas",
    "Schreiber",
    "Graf",
    "Schulte",
    "Dietrich",
    "Ziegler",
    "Kuhn",
    "Kühn",
    "Pohl",
    "Engel",
    "Horn",
    "Busch",
    "Bergmann",
    "Thomas",
    "Voigt",
    "Sauer",
    "Arnold",
    "Wolff",
    "Pfeiffer"
)

val firstNames: List<String> = listOf(
    "Albert",
    "Brigitte",
    "Chris",
    "Donald",
    "Elsa",
    "Friedrich",
    "Günther",
    "Hans",
    "Isa",
    "Justin",
    "Kirsten",
    "Luis",
    "Max",
    "Norbert",
    "Olaf",
    "Patrick",
    "Quentin",
    "Richard",
    "Steffan",
    "Tim",
    "Ulf",
    "Valentin",
    "Wilhelm",
    "Xaver",
    "Yoshi",
    "Zoe"
)

// From https://de.wikipedia.org/wiki/Liste_der_Staaten_der_Erde
val countries: List<String> = listOf(
    "Abchasien",
    "Afghanistan",
    "Ägypten",
    "Albanien",
    "Algerien",
    "Andorra",
    "Angola",
    "Antigua und Barbuda",
    "Äquatorialguinea",
    "Argentinien",
    "Armenien",
    "Aserbaidschan",
    "Äthiopien",
    "Australien",
    "Bahamas",
    "Bahrain",
    "Bangladesch",
    "Barbados",
    "Belarus",
    "Belgien",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivien",
    "Bosnien und Herzegowina",
    "Botswana",
    "Brasilien",
    "Brunei",
    "Bulgarien",
    "Burkina Faso",
    "Burundi",
    "Chile",
    "China, Republik",
    "China, Volksrepublik",
    "Cookinseln",
    "Costa Rica",
    "Dänemark",
    "Deutschland",
    "Dominica",
    "Dominikanische Republik",
    "Dschibuti",
    "El Salvador",
    "Elfenbeinküste",
    "Eritrea",
    "Estland",
    "Eswatini",
    "Fidschi",
    "Finnland",
    "Frankreich",
    "Gabun",
    "Gambia",
    "Georgien",
    "Ghana",
    "Grenada",
    "Griechenland",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Indien",
    "Indonesien",
    "Irak",
    "Iran",
    "Irland",
    "Island",
    "Israel",
    "Italien",
    "Jamaika",
    "Japan",
    "Jemen",
    "Jordanien",
    "Kambodscha",
    "Kamerun",
    "Kanada",
    "Kap Verde",
    "Kasachstan",
    "Katar",
    "Kenia",
    "Kirgistan",
    "Kiribati",
    "Kolumbien",
    "Komoren",
    "Kongo, Demokratische Republik",
    "Kongo, Republik",
    "Korea, Nord",
    "Korea, Süd",
    "Kosovo",
    "Kroatien",
    "Kuba",
    "Kuwait",
    "Laos",
    "Lesotho",
    "Lettland",
    "Libanon",
    "Liberia",
    "Libyen",
    "Liechtenstein",
    "Litauen",
    "Luxemburg",
    "Madagaskar",
    "Malawi",
    "Malaysia",
    "Malediven",
    "Mali",
    "Malta",
    "Marokko",
    "Marshallinseln",
    "Mauretanien",
    "Mauritius",
    "Mexiko",
    "Mikronesien",
    "Moldau",
    "Monaco",
    "Mongolei",
    "Montenegro",
    "Mosambik",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Neuseeland",
    "Nicaragua",
    "Niederlande",
    "Niger",
    "Nigeria",
    "Niue",
    "Nordmazedonien",
    "Nordzypern",
    "Norwegen",
    "Oman",
    "Östereich",
    "Osttimor",
    "Pakistan",
    "Palästina",
    "Palau",
    "Panama",
    "Papua-Neuguinea",
    "Paraguay",
    "Peru",
    "Philippinen",
    "Polen",
    "Portugal",
    "Ruanda",
    "Rumänien",
    "Russland",
    "Salomonen",
    "Sambia",
    "Samoa",
    "San Marino",
    "São Tomé und Príncipe",
    "Saudi-Arabien",
    "Schweden",
    "Schweiz",
    "Senegal",
    "Serbien",
    "Seychellen",
    "Sierra Leone",
    "Simbabwe",
    "Singapur",
    "Slowakei",
    "Slowenien",
    "Somalia",
    "Somaliland",
    "Spanien",
    "Sri Lanka",
    "St. Kitts und Nevis",
    "St. Lucia",
    "St. Vincent und die Grenadinen",
    "Südafrika",
    "Sudan",
    "Südossetien",
    "Südsudan",
    "Suriname",
    "Syrien",
    "Tadschikistan",
    "Tansania",
    "Thailand",
    "Togo",
    "Tonga",
    "Transnistrien",
    "Trinidad und Tobago",
    "Tschad",
    "Tschechien",
    "Tunesien",
    "Türkei",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "Ungarn",
    "Uruguay",
    "Usbekistan",
    "Vanuatu",
    "Vatikanstadt",
    "Venezuela",
    "Vereinigte Arabische Emirate",
    "Vereinigte Staaten",
    "Vereinigtes Königreich",
    "Vietnam",
    "Westsahara",
    "Zentral afrikanische Republik",
    "Zypern"
)

// From https://de.wikipedia.org/wiki/Liste_von_Ausbildungsberufen
val occupations: List<String> = listOf(
    "Biologiemodellmacher",
    "Bootsbauer",
    "Bürsten- und Pinselmacher",
    "Drechsler",
    "Fachkraft für Holz- und Bautenschutzarbeiten",
    "Flechtwerkgestalter",
    "Holzbearbeitungsmechaniker",
    "Holzbildhauer",
    "Holzmechaniker",
    "Holzspielzeugmacher",
    "Holz- und Bautenschützer",
    "Böttcher",
    "Leichtflugzeugbauer",
    "Rollladen- und Sonnenschutzmechatroniker",
    "Schirmmacher",
    "Spielzeughersteller",
    "Technischer Modellbauer",
    "Tischler",
    "Schreiner",
    "Bogenmacher",
    "Geigenbauer",
    "Handzuginstrumentenmacher",
    "Holzblasinstrumentenmacher",
    "Klavier- und Cembalobauer",
    "Metallblasinstrumentenmacher",
    "Orgelbauer",
    "Zupfinstrumentenmacher"
)

// From https://de.wikipedia.org/wiki/Liste_der_gr%C3%B6%C3%9Ften_St%C3%A4dte_Europas
val cities: List<String> = listOf(
    "Istanbul",
    "Moskau",
    "London",
    "Sankt Petersburg",
    "Berlin",
    "Madrid",
    "Kiew",
    "Rom",
    "Paris",
    "Wien",
    "Minsk",
    "Hamburg",
    "Warschau",
    "Bukarest",
    "Budapest",
    "Barcelona",
    "München",
    "Charkiw",
    "Mailand",
    "Prag",
    "Sofia",
    "Kasan",
    "Nischni Nowgorod",
    "Belgrad",
    "Birmingham",
    "Samara",
    "Rostow am Don",
    "Ufa",
    "Köln",
    "Woronesch",
    "Perm",
    "Odessa",
    "Wolgograd",
    "Stockholm",
    "Dnipro",
    "Krasnodar",
    "Amsterdam",
    "Neapel",
    "Donezk",
    "Marseille",
    "Tirana",
    "Turin",
    "Saratow",
    "Leeds",
    "Krakau",
    "Valencia",
    "Frankfurt am Main",
    "Zagreb",
    "Lwiw",
    "Saporischschja",
    "Oslo",
    "Toljatti",
    "Sevilla",
    "Chișinău",
    "Breslau",
    "Saragossa",
    "Rotterdam",
    "Helsinki",
    "Łódź",
    "Kopenhagen",
    "Ischewsk",
    "Athen",
    "Palermo",
    "Stuttgart",
    "Düsseldorf",
    "Uljanowsk",
    "Glasgow",
    "Leipzig",
    "Riga",
    "Machatschkala",
    "Krywyj Rih",
    "Jaroslawl",
    "Göteborg",
    "Dortmund",
    "Dublin",
    "Essen",
    "Málaga",
    "Vilnius",
    "Bremen",
    "Orenburg",
    "Manchester",
    "Sheffield",
    "Dresden",
    "Den Haag",
    "Genua",
    "Bradford",
    "Hannover",
    "Lissabon",
    "Posen",
    "Rjasan",
    "Nabereschnyje Tschelny",
    "Antwerpen",
    "Skopje",
    "Nürnberg",
    "Astrachan",
    "Lyon",
    "Kirow",
    "Pensa",
    "Edinburgh",
    "Balaschicha",
    "Lipezk",
    "Duisburg",
    "Homel"
)

