/**
  DROP TABLES IF THEY EXIT
 */
DROP TABLE PERSON_DATA_A;
DROP TABLE PERSON_DATA_B;
DROP TABLE PERSON_DATA_C;
DROP TABLE PERSON_DATA_D;

/*
  Create TABLES
 */
CREATE TABLE PERSON_DATA_A
(
    name       varchar(50),
    first_name varchar(50),
    postcode   varchar(5),
    city       varchar(50),
    country    varchar(50),
    occupation varchar(100)
);

CREATE TABLE PERSON_DATA_B
(
    name       varchar(50),
    first_name varchar(50),
    postcode   varchar(5),
    city       varchar(50),
    country    varchar(50),
    occupation varchar(100)
);

CREATE TABLE PERSON_DATA_C
(
    name       varchar(50),
    first_name varchar(50),
    postcode   varchar(5),
    city       varchar(50),
    country    varchar(50),
    occupation varchar(100)
);

CREATE TABLE PERSON_DATA_D
(
    name       varchar(50),
    first_name varchar(50),
    postcode   varchar(5),
    city       varchar(50),
    country    varchar(50),
    occupation varchar(100)
);

/**
  FILL TABLES WITH DUMMY DATA
 */


INSERT INTO PERSON_DATA_A (name, first_name, postcode, city, country, occupation)
VALUES ('Kraus', 'Max', '85039', 'Hamburg', 'Transnistrien', 'Tischler'),
       ('Lang', 'Kirsten', '95653', 'Homel', 'Honduras', 'Tischler'),
       ('Müller', 'Tim', '59157', 'Manchester', 'Bhutan', 'Bürsten- und Pinselmacher'),
       ('Fuchs', 'Brigitte', '60214', 'Leipzig', 'Bosnien und Herzegowina', 'Holzblasinstrumentenmacher'),
       ('Kraus', 'Isa', '80607', 'Hannover', 'Östereich', 'Orgelbauer'),
       ('Walter', 'Tim', '32170', 'Pensa', 'Sierra Leone', 'Holzbearbeitungsmechaniker'),
       ('Voigt', 'Wilhelm', '57318', 'Amsterdam', 'Gabun', 'Holzspielzeugmacher'),
       ('Schneider', 'Kirsten', '70538', 'Nürnberg', 'Slowenien', 'Zupfinstrumentenmacher'),
       ('Schröder', 'Chris', '86699', 'Perm', 'Cookinseln', 'Leichtflugzeugbauer'),
       ('Möller', 'Ulf', '53451', 'Essen', 'Uganda', 'Handzuginstrumentenmacher'),
       ('Fischer', 'Richard', '89473', 'Manchester', 'Schweden', 'Drechsler'),
       ('Lehmann', 'Tim', '36658', 'Kirow', 'St. Lucia', 'Schirmmacher'),
       ('Ziegler', 'Brigitte', '69637', 'Paris', 'Dominica', 'Holz- und Bautenschützer'),
       ('Schuster', 'Steffan', '38817', 'Valencia', 'Westsahara', 'Flechtwerkgestalter'),
       ('Schwarz', 'Kirsten', '67475', 'Berlin', 'Nepal', 'Schreiner'),
       ('Marin', 'Tim', '67841', 'Frankfurt am Main', 'Türkei', 'Holzblasinstrumentenmacher'),
       ('Vogt', 'Kirsten', '53216', 'Rostow am Don', 'Philippinen', 'Schirmmacher'),
       ('Schwarz', 'Norbert', '48256', 'Tirana', 'Saudi-Arabien', 'Holz- und Bautenschützer'),
       ('Jäger', 'Kirsten', '31799', 'Sheffield', 'Vanuatu', 'Holzblasinstrumentenmacher'),
       ('Köhler', 'Wilhelm', '92947', 'Bremen', 'Panama', 'Tischler'),
       ('Schulze', 'Brigitte', '96337', 'Valencia', 'Kuwait', 'Bürsten- und Pinselmacher'),
       ('Möller', 'Hans', '64160', 'Hannover', 'Jemen', 'Holz- und Bautenschützer'),
       ('Herrmann', 'Kirsten', '30669', 'Rotterdam', 'Oman', 'Schirmmacher'),
       ('Fischer', 'Elsa', '95850', 'Odessa', 'Südafrika', 'Handzuginstrumentenmacher'),
       ('Groß', 'Isa', '19955', 'Toljatti', 'Trinidad und Tobago', 'Handzuginstrumentenmacher'),
       ('Thomas', 'Yoshi', '93821', 'Lissabon', 'Niger', 'Holzbildhauer'),
       ('Stein', 'Norbert', '53606', 'Leipzig', 'Malta', 'Böttcher'),
       ('Thomas', 'Justin', '15459', 'Athen', 'Zypern', 'Geigenbauer'),
       ('Graf', 'Patrick', '49601', 'Riga', 'Polen', 'Geigenbauer'),
       ('Böhm', 'Norbert', '78807', 'Machatschkala', 'Vatikanstadt', 'Bootsbauer'),
       ('Arnold', 'Isa', '89247', 'Saporischschja', 'Tansania', 'Holzblasinstrumentenmacher'),
       ('Friedrich', 'Valentin', '26828', 'Prag', 'Bhutan', 'Schirmmacher'),
       ('Frank', 'Günther', '61179', 'Birmingham', 'Moldau', 'Flechtwerkgestalter'),
       ('Wolff', 'Chris', '78723', 'Istanbul', 'Guyana', 'Schreiner'),
       ('Horn', 'Elsa', '28793', 'Den Haag', 'Bolivien', 'Spielzeughersteller'),
       ('Winkler', 'Ulf', '78586', 'Göteborg', 'Fidschi', 'Flechtwerkgestalter'),
       ('Jäger', 'Albert', '60317', 'Lipezk', 'Zentral afrikanische Republik', 'Handzuginstrumentenmacher'),
       ('Krause', 'Olaf', '83272', 'Berlin', 'Kolumbien', 'Holzbildhauer'),
       ('Richter', 'Yoshi', '29681', 'Stuttgart', 'Ungarn', 'Flechtwerkgestalter'),
       ('Lange', 'Richard', '57504', 'Leipzig', 'Mauretanien', 'Spielzeughersteller'),
       ('Werner', 'Donald', '61957', 'Chișinău', 'Syrien', 'Geigenbauer'),
       ('Möller', 'Quentin', '33559', 'Prag', 'Peru', 'Holz- und Bautenschützer'),
       ('Schulte', 'Kirsten', '73507', 'Lwiw', 'Kenia', 'Schirmmacher'),
       ('Schwarz', 'Günther', '37440', 'München', 'Elfenbeinküste', 'Bogenmacher'),
       ('Schuster', 'Günther', '78469', 'Saratow', 'Nigeria', 'Bootsbauer'),
       ('Horn', 'Patrick', '15284', 'Moskau', 'Island', 'Fachkraft für Holz- und Bautenschutzarbeiten'),
       ('Schmitz', 'Albert', '13427', 'Kirow', 'Costa Rica', 'Tischler'),
       ('Scholz', 'Max', '36017', 'Toljatti', 'Oman', 'Tischler'),
       ('Marin', 'Ulf', '78266', 'Madrid', 'Suriname', 'Holzmechaniker'),
       ('Böhm', 'Zoe', '46996', 'Vilnius', 'Philippinen', 'Orgelbauer'),
       ('Lange', 'Elsa', '76699', 'Posen', 'Honduras', 'Holzblasinstrumentenmacher'),
       ('Huber', 'Isa', '70660', 'Homel', 'Ägypten', 'Holzspielzeugmacher'),
       ('Friedrich', 'Ulf', '52474', 'Toljatti', 'Uruguay', 'Orgelbauer'),
       ('Wagner', 'Wilhelm', '94002', 'Minsk', 'Nigeria', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Schulz', 'Kirsten', '59553', 'Dortmund', 'Costa Rica', 'Technischer Modellbauer'),
       ('Schäfer', 'Justin', '42813', 'Homel', 'Algerien', 'Schreiner'),
       ('Möller', 'Elsa', '86569', 'Krakau', 'Kenia', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Voigt', 'Richard', '68747', 'Leeds', 'Mauretanien', 'Bürsten- und Pinselmacher'),
       ('Winkler', 'Friedrich', '21447', 'Uljanowsk', 'Tansania', 'Holzblasinstrumentenmacher'),
       ('Berger', 'Wilhelm', '84177', 'Ischewsk', 'Bahrain', 'Holzblasinstrumentenmacher'),
       ('Becker', 'Quentin', '63384', 'Zagreb', 'Thailand', 'Klavier- und Cembalobauer'),
       ('Bauer', 'Hans', '14178', 'Turin', 'Moldau', 'Tischler'),
       ('Meyer', 'Wilhelm', '31152', 'Nabereschnyje Tschelny', 'Sri Lanka', 'Metallblasinstrumentenmacher'),
       ('Frank', 'Zoe', '50570', 'Dublin', 'Tunesien', 'Technischer Modellbauer'),
       ('Schubert', 'Kirsten', '24944', 'Athen', 'Tuvalu', 'Fachkraft für Holz- und Bautenschutzarbeiten'),
       ('Möller', 'Richard', '70490', 'Posen', 'Jemen', 'Flechtwerkgestalter'),
       ('Hofmann', 'Ulf', '25546', 'Duisburg', 'Kolumbien', 'Schirmmacher'),
       ('Schröder', 'Friedrich', '54236', 'Den Haag', 'Neuseeland', 'Leichtflugzeugbauer'),
       ('Friedrich', 'Justin', '95666', 'Nabereschnyje Tschelny', 'Luxemburg', 'Metallblasinstrumentenmacher'),
       ('Schäfer', 'Albert', '73570', 'Rotterdam', 'Nepal', 'Geigenbauer'),
       ('Marin', 'Isa', '59816', 'Marseille', 'Estland', 'Holzblasinstrumentenmacher'),
       ('Maier', 'Tim', '31048', 'Lyon', 'Sierra Leone', 'Holzbearbeitungsmechaniker'),
       ('Marin', 'Luis', '14027', 'Budapest', 'Saudi-Arabien', 'Leichtflugzeugbauer'),
       ('Marin', 'Justin', '93342', 'Ufa', 'Südsudan', 'Spielzeughersteller'),
       ('Schröder', 'Norbert', '13856', 'Toljatti', 'Irland', 'Bürsten- und Pinselmacher'),
       ('Wolff', 'Donald', '57916', 'Lwiw', 'Dschibuti', 'Holzspielzeugmacher'),
       ('Lorenz', 'Richard', '15348', 'Krakau', 'Vatikanstadt', 'Drechsler'),
       ('Möller', 'Isa', '25904', 'Vilnius', 'Kenia', 'Schreiner'),
       ('Seidel', 'Olaf', '95917', 'Krakau', 'Angola', 'Holzblasinstrumentenmacher'),
       ('Peters', 'Isa', '18899', 'Orenburg', 'Griechenland', 'Spielzeughersteller'),
       ('Fischer', 'Justin', '52268', 'Den Haag', 'Armenien', 'Fachkraft für Holz- und Bautenschutzarbeiten'),
       ('Schmidt', 'Max', '17200', 'Krywyj Rih', 'Kap Verde', 'Schirmmacher'),
       ('Berger', 'Isa', '90253', 'Krakau', 'Sierra Leone', 'Holz- und Bautenschützer'),
       ('Beck', 'Zoe', '91816', 'Tirana', 'Korea, Nord', 'Holzbildhauer'),
       ('Schumacher', 'Friedrich', '19222', 'Leeds', 'Guatemala', 'Biologiemodellmacher'),
       ('Simon', 'Donald', '16059', 'Berlin', 'Benin', 'Orgelbauer'),
       ('Schäfer', 'Friedrich', '40703', 'Marseille', 'Seychellen', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Schwarz', 'Donald', '83133', 'Uljanowsk', 'Seychellen', 'Zupfinstrumentenmacher'),
       ('Simon', 'Norbert', '21154', 'Oslo', 'Mexiko', 'Technischer Modellbauer'),
       ('Bergmann', 'Zoe', '49994', 'Prag', 'Turkmenistan', 'Bürsten- und Pinselmacher'),
       ('Baumann', 'Valentin', '95948', 'Dresden', 'Tuvalu', 'Schreiner'),
       ('Bauer', 'Ulf', '19377', 'Skopje', 'St. Vincent und die Grenadinen', 'Klavier- und Cembalobauer'),
       ('Weiß', 'Hans', '99661', 'Leeds', 'Syrien', 'Handzuginstrumentenmacher'),
       ('Fischer', 'Norbert', '40621', 'Sofia', 'Barbados', 'Holzbearbeitungsmechaniker'),
       ('Lang', 'Ulf', '46241', 'Saporischschja', 'Jordanien', 'Drechsler'),
       ('Arnold', 'Tim', '79150', 'Kasan', 'Belarus', 'Bootsbauer'),
       ('Bauer', 'Ulf', '54201', 'Tirana', 'Sierra Leone', 'Leichtflugzeugbauer'),
       ('Möller', 'Brigitte', '41572', 'Amsterdam', 'Libanon', 'Fachkraft für Holz- und Bautenschutzarbeiten'),
       ('Kaiser', 'Patrick', '69689', 'Madrid', 'Indien', 'Bootsbauer'),
       ('Meyer', 'Günther', '41762', 'Sankt Petersburg', 'Griechenland', 'Schirmmacher'),
       ('Hofmann', 'Ulf', '67636', 'Rotterdam', 'Singapur', 'Bootsbauer');

INSERT INTO PERSON_DATA_B (name, first_name, postcode, city, country, occupation)
VALUES ('Krause', 'Chris', '79907', 'Manchester', 'Guinea', 'Zupfinstrumentenmacher'),
       ('Fuchs', 'Quentin', '19924', 'Amsterdam', 'Portugal', 'Holzblasinstrumentenmacher'),
       ('Hofmann', 'Ulf', '27237', 'Kopenhagen', 'Kasachstan', 'Bürsten- und Pinselmacher'),
       ('Günther', 'Norbert', '67647', 'Málaga', 'Antigua und Barbuda', 'Drechsler'),
       ('Meier', 'Zoe', '36914', 'Rotterdam', 'São Tomé und Príncipe', 'Geigenbauer'),
       ('Schäfer', 'Elsa', '55841', 'Zagreb', 'Russland', 'Bogenmacher'),
       ('Hoffmann', 'Donald', '87342', 'Amsterdam', 'Kosovo', 'Holz- und Bautenschützer'),
       ('Fischer', 'Kirsten', '36025', 'Essen', 'El Salvador', 'Holzbildhauer'),
       ('Berger', 'Friedrich', '50206', 'Málaga', 'Indien', 'Metallblasinstrumentenmacher'),
       ('Seidel', 'Yoshi', '79244', 'Dublin', 'Bolivien', 'Technischer Modellbauer'),
       ('Brandt', 'Valentin', '48755', 'Dortmund', 'Salomonen', 'Flechtwerkgestalter'),
       ('Hartmann', 'Valentin', '81994', 'Posen', 'Guatemala', 'Bootsbauer'),
       ('Lorenz', 'Kirsten', '63071', 'Marseille', 'Lettland', 'Fachkraft für Holz- und Bautenschutzarbeiten'),
       ('Otto', 'Steffan', '19480', 'Ischewsk', 'Pakistan', 'Böttcher'),
       ('Maier', 'Friedrich', '11921', 'Wien', 'Vereinigtes Königreich', 'Holzbildhauer'),
       ('Stein', 'Yoshi', '12052', 'Sheffield', 'Mosambik', 'Flechtwerkgestalter'),
       ('Walter', 'Max', '29603', 'Moskau', 'Madagaskar', 'Böttcher'),
       ('Roth', 'Isa', '56801', 'Breslau', 'Polen', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Meyer', 'Xaver', '18107', 'Samara', 'Türkei', 'Schirmmacher'),
       ('Schäfer', 'Richard', '52196', 'Sheffield', 'Kambodscha', 'Schirmmacher'),
       ('Herrmann', 'Chris', '90051', 'Orenburg', 'Kambodscha', 'Holzblasinstrumentenmacher'),
       ('Sommer', 'Justin', '25614', 'Valencia', 'Burkina Faso', 'Biologiemodellmacher'),
       ('Schwarz', 'Albert', '30455', 'Machatschkala', 'Liechtenstein', 'Technischer Modellbauer'),
       ('Dietrich', 'Albert', '17044', 'Málaga', 'Ghana', 'Holzblasinstrumentenmacher'),
       ('Roth', 'Albert', '56664', 'Helsinki', 'Mauritius', 'Holzspielzeugmacher'),
       ('Ludwig', 'Xaver', '25243', 'Odessa', 'Belize', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Schulte', 'Justin', '29349', 'Düsseldorf', 'China, Republik', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Schmid', 'Justin', '76082', 'Belgrad', 'Slowenien', 'Geigenbauer'),
       ('Seidel', 'Friedrich', '84783', 'Leeds', 'Marshallinseln', 'Böttcher'),
       ('Lange', 'Donald', '96633', 'Homel', 'Komoren', 'Holzbildhauer'),
       ('Lorenz', 'Justin', '79583', 'Bradford', 'Dschibuti', 'Schirmmacher'),
       ('Stein', 'Olaf', '78863', 'Leipzig', 'Äthiopien', 'Biologiemodellmacher'),
       ('Brandt', 'Kirsten', '13473', 'Leipzig', 'Liberia', 'Holzblasinstrumentenmacher'),
       ('Lange', 'Kirsten', '23616', 'Lyon', 'Schweiz', 'Holzblasinstrumentenmacher'),
       ('Schmid', 'Günther', '89974', 'Bukarest', 'Eritrea', 'Bürsten- und Pinselmacher'),
       ('Horn', 'Brigitte', '35184', 'Antwerpen', 'Honduras', 'Geigenbauer'),
       ('Köhler', 'Patrick', '90856', 'Wien', 'Belize', 'Holz- und Bautenschützer'),
       ('Roth', 'Wilhelm', '34673', 'Rotterdam', 'Australien', 'Drechsler'),
       ('Jung', 'Albert', '61288', 'Málaga', 'Philippinen', 'Holz- und Bautenschützer'),
       ('Hartmann', 'Elsa', '13362', 'Madrid', 'Libanon', 'Flechtwerkgestalter'),
       ('Meier', 'Elsa', '69789', 'Rostow am Don', 'Madagaskar', 'Technischer Modellbauer'),
       ('Richter', 'Richard', '96171', 'Bradford', 'Ghana', 'Handzuginstrumentenmacher'),
       ('Wolff', 'Zoe', '14589', 'Belgrad', 'San Marino', 'Bürsten- und Pinselmacher'),
       ('Müller', 'Richard', '56359', 'Tirana', 'Guinea-Bissau', 'Leichtflugzeugbauer'),
       ('Schreiber', 'Patrick', '53490', 'Vilnius', 'Vereinigtes Königreich', 'Holzmechaniker'),
       ('Groß', 'Olaf', '90614', 'Jaroslawl', 'Israel', 'Zupfinstrumentenmacher'),
       ('Neumann', 'Brigitte', '64922', 'London', 'Guyana', 'Orgelbauer'),
       ('Bauer', 'Ulf', '96819', 'Den Haag', 'Botswana', 'Holzspielzeugmacher'),
       ('Pfeiffer', 'Wilhelm', '85150', 'Sheffield', 'Burundi', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Beck', 'Steffan', '68425', 'Prag', 'Armenien', 'Flechtwerkgestalter'),
       ('Pfeiffer', 'Chris', '87217', 'Donezk', 'Senegal', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Peters', 'Yoshi', '73993', 'Hamburg', 'Tansania', 'Flechtwerkgestalter'),
       ('Schulz', 'Norbert', '49173', 'Berlin', 'Mexiko', 'Handzuginstrumentenmacher'),
       ('Simon', 'Norbert', '20311', 'Warschau', 'Dominica', 'Holzspielzeugmacher'),
       ('Vogt', 'Brigitte', '43989', 'Kopenhagen', 'Myanmar', 'Orgelbauer'),
       ('Schmidt', 'Isa', '76138', 'Pensa', 'Westsahara', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Frank', 'Brigitte', '12054', 'Paris', 'Mongolei', 'Zupfinstrumentenmacher'),
       ('Schubert', 'Chris', '25128', 'Köln', 'Uruguay', 'Spielzeughersteller'),
       ('Groß', 'Isa', '58922', 'Krywyj Rih', 'Kuba', 'Fachkraft für Holz- und Bautenschutzarbeiten'),
       ('Brandt', 'Albert', '85445', 'Machatschkala', 'Mauritius', 'Metallblasinstrumentenmacher'),
       ('Schröder', 'Steffan', '73533', 'London', 'Ungarn', 'Schirmmacher'),
       ('Krüger', 'Yoshi', '62212', 'Vilnius', 'Sambia', 'Holzbearbeitungsmechaniker'),
       ('Weber', 'Isa', '85280', 'Rotterdam', 'Somaliland', 'Holz- und Bautenschützer'),
       ('Fuchs', 'Elsa', '59794', 'Balaschicha', 'Nicaragua', 'Orgelbauer'),
       ('Weiß', 'Patrick', '92694', 'Sevilla', 'Guatemala', 'Böttcher'),
       ('Haas', 'Ulf', '81483', 'Posen', 'Afghanistan', 'Holzbildhauer'),
       ('Mayer', 'Elsa', '12596', 'Málaga', 'Iran', 'Orgelbauer'),
       ('Koch', 'Ulf', '42349', 'Balaschicha', 'Afghanistan', 'Leichtflugzeugbauer'),
       ('Beck', 'Steffan', '32378', 'Kasan', 'Somalia', 'Fachkraft für Holz- und Bautenschutzarbeiten'),
       ('Braun', 'Isa', '59065', 'München', 'Katar', 'Holzbearbeitungsmechaniker'),
       ('Thomas', 'Zoe', '37474', 'Homel', 'Niederlande', 'Orgelbauer'),
       ('Heinrich', 'Steffan', '45633', 'Krywyj Rih', 'Türkei', 'Schreiner'),
       ('Horn', 'Xaver', '12302', 'Kopenhagen', 'Luxemburg', 'Holzbildhauer'),
       ('Seidel', 'Brigitte', '95641', 'Frankfurt am Main', 'Korea, Nord', 'Bürsten- und Pinselmacher'),
       ('Schneider', 'Günther', '42039', 'Rom', 'Vereinigte Arabische Emirate', 'Böttcher'),
       ('Kühn', 'Brigitte', '92886', 'Posen', 'Honduras', 'Spielzeughersteller'),
       ('Jung', 'Max', '32963', 'Machatschkala', 'Kroatien', 'Handzuginstrumentenmacher'),
       ('Fischer', 'Brigitte', '93186', 'Rom', 'Somalia', 'Holzspielzeugmacher'),
       ('Schulz', 'Wilhelm', '72680', 'Stuttgart', 'Kroatien', 'Handzuginstrumentenmacher'),
       ('Zimmermann', 'Xaver', '32257', 'Kiew', 'Guyana', 'Böttcher'),
       ('Frank', 'Valentin', '52398', 'Dresden', 'Kamerun', 'Spielzeughersteller'),
       ('Pfeiffer', 'Steffan', '49197', 'Málaga', 'Neuseeland', 'Böttcher'),
       ('Jung', 'Elsa', '48749', 'Posen', 'Italien', 'Leichtflugzeugbauer'),
       ('Mayer', 'Chris', '24001', 'Frankfurt am Main', 'Sambia', 'Holzblasinstrumentenmacher'),
       ('Wolff', 'Elsa', '85989', 'Machatschkala', 'Bulgarien', 'Handzuginstrumentenmacher'),
       ('Mayer', 'Albert', '12891', 'Odessa', 'Vatikanstadt', 'Drechsler'),
       ('Maier', 'Justin', '98758', 'Zagreb', 'Serbien', 'Technischer Modellbauer'),
       ('Wagner', 'Xaver', '41966', 'Leipzig', 'Kongo, Republik', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Schröder', 'Justin', '11014', 'Vilnius', 'Mexiko', 'Orgelbauer'),
       ('Mayer', 'Richard', '19963', 'Berlin', 'Aserbaidschan', 'Holzbearbeitungsmechaniker'),
       ('Schulze', 'Elsa', '27551', 'Homel', 'Tuvalu', 'Holz- und Bautenschützer'),
       ('Schmitz', 'Xaver', '70733', 'Nischni Nowgorod', 'Südafrika', 'Leichtflugzeugbauer'),
       ('Wolff', 'Ulf', '45171', 'Wien', 'Iran', 'Böttcher'),
       ('Werner', 'Valentin', '90057', 'Tirana', 'San Marino', 'Flechtwerkgestalter'),
       ('Schubert', 'Luis', '77553', 'Krasnodar', 'Seychellen', 'Leichtflugzeugbauer'),
       ('Heinrich', 'Valentin', '80450', 'Dresden', 'Papua-Neuguinea', 'Bogenmacher'),
       ('Baumann', 'Max', '22976', 'Helsinki', 'Andorra', 'Holzbearbeitungsmechaniker'),
       ('Busch', 'Elsa', '25326', 'Barcelona', 'Jemen', 'Böttcher'),
       ('Fischer', 'Elsa', '35048', 'Kirow', 'Tansania', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Herrmann', 'Isa', '18833', 'Machatschkala', 'Simbabwe', 'Metallblasinstrumentenmacher'),
       ('Baumann', 'Hans', '20590', 'Málaga', 'Nicaragua', 'Holzmechaniker');

INSERT INTO PERSON_DATA_C (name, first_name, postcode, city, country, occupation)
VALUES ('Lang', 'Yoshi', '44255', 'Palermo', 'Lettland', 'Metallblasinstrumentenmacher'),
       ('Huber', 'Zoe', '42039', 'Chișinău', 'Saudi-Arabien', 'Metallblasinstrumentenmacher'),
       ('Arnold', 'Wilhelm', '90720', 'Nürnberg', 'Vereinigtes Königreich', 'Flechtwerkgestalter'),
       ('Krause', 'Günther', '96736', 'Pensa', 'Papua-Neuguinea', 'Holz- und Bautenschützer'),
       ('Ludwig', 'Tim', '93275', 'London', 'Costa Rica', 'Holz- und Bautenschützer'),
       ('Hahn', 'Olaf', '87002', 'Posen', 'Polen', 'Bootsbauer'),
       ('Wolf', 'Luis', '59843', 'Helsinki', 'Philippinen', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Busch', 'Patrick', '99860', 'Astrachan', 'Malta', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Schreiber', 'Justin', '24480', 'Göteborg', 'Nepal', 'Böttcher'),
       ('Becker', 'Wilhelm', '54033', 'Jaroslawl', 'Costa Rica', 'Holzspielzeugmacher'),
       ('Braun', 'Kirsten', '69699', 'Saporischschja', 'Irland', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Jäger', 'Norbert', '98681', 'Krasnodar', 'Andorra', 'Fachkraft für Holz- und Bautenschutzarbeiten'),
       ('Kraus', 'Friedrich', '85682', 'Nabereschnyje Tschelny', 'Osttimor', 'Tischler'),
       ('Berger', 'Norbert', '11120', 'Wolgograd', 'Nepal', 'Biologiemodellmacher'),
       ('Winter', 'Friedrich', '98428', 'Leipzig', 'Sambia', 'Holzbearbeitungsmechaniker'),
       ('Vogel', 'Norbert', '85829', 'Dresden', 'Vatikanstadt', 'Drechsler'),
       ('Schmidt', 'Xaver', '93345', 'Łódź', 'Oman', 'Flechtwerkgestalter'),
       ('Fischer', 'Zoe', '91795', 'Göteborg', 'Russland', 'Handzuginstrumentenmacher'),
       ('Krüger', 'Elsa', '33298', 'Wolgograd', 'Äthiopien', 'Technischer Modellbauer'),
       ('Engel', 'Ulf', '55273', 'Bukarest', 'Benin', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Marin', 'Günther', '42765', 'Donezk', 'Ruanda', 'Schirmmacher'),
       ('Kühn', 'Luis', '75999', 'Orenburg', 'Sambia', 'Klavier- und Cembalobauer'),
       ('Winkler', 'Xaver', '49532', 'Leipzig', 'Afghanistan', 'Leichtflugzeugbauer'),
       ('Beck', 'Zoe', '51941', 'Homel', 'Korea, Süd', 'Schreiner'),
       ('Wolff', 'Yoshi', '71066', 'Riga', 'Ägypten', 'Schirmmacher'),
       ('Schulte', 'Luis', '74577', 'Lwiw', 'Bolivien', 'Leichtflugzeugbauer'),
       ('Jung', 'Valentin', '39645', 'Stockholm', 'Griechenland', 'Holzbildhauer'),
       ('Schwarz', 'Norbert', '60351', 'Duisburg', 'Slowakei', 'Metallblasinstrumentenmacher'),
       ('Franke', 'Max', '91169', 'Turin', 'Thailand', 'Schirmmacher'),
       ('Sommer', 'Steffan', '10389', 'Krywyj Rih', 'Libanon', 'Holzblasinstrumentenmacher'),
       ('Zimmermann', 'Donald', '90978', 'Neapel', 'Turkmenistan', 'Klavier- und Cembalobauer'),
       ('Keller', 'Günther', '49638', 'Málaga', 'Ghana', 'Bürsten- und Pinselmacher'),
       ('Graf', 'Isa', '89402', 'Budapest', 'Pakistan', 'Flechtwerkgestalter'),
       ('Ziegler', 'Kirsten', '43685', 'Ufa', 'Malawi', 'Technischer Modellbauer'),
       ('Winter', 'Olaf', '52709', 'Stuttgart', 'Uruguay', 'Böttcher'),
       ('Seidel', 'Chris', '57134', 'Bremen', 'Mongolei', 'Holzbearbeitungsmechaniker'),
       ('Groß', 'Elsa', '55599', 'Tirana', 'Bhutan', 'Bürsten- und Pinselmacher'),
       ('Stein', 'Olaf', '83890', 'Oslo', 'Bolivien', 'Fachkraft für Holz- und Bautenschutzarbeiten'),
       ('Schmitz', 'Isa', '24129', 'Lwiw', 'Senegal', 'Bürsten- und Pinselmacher'),
       ('Neumann', 'Brigitte', '45812', 'Lissabon', 'Antigua und Barbuda', 'Holzbildhauer'),
       ('Winkler', 'Isa', '49714', 'Rotterdam', 'Kuwait', 'Holzbildhauer'),
       ('Kuhn', 'Quentin', '87404', 'Lissabon', 'Salomonen', 'Bürsten- und Pinselmacher'),
       ('Bergmann', 'Wilhelm', '95221', 'Homel', 'Andorra', 'Metallblasinstrumentenmacher'),
       ('Klein', 'Tim', '42678', 'Essen', 'Vereinigte Arabische Emirate', 'Bootsbauer'),
       ('Schulz', 'Brigitte', '21422', 'Pensa', 'Irak', 'Fachkraft für Holz- und Bautenschutzarbeiten'),
       ('Vogt', 'Steffan', '93990', 'Essen', 'St. Vincent und die Grenadinen', 'Holzspielzeugmacher'),
       ('Jäger', 'Chris', '68826', 'Rotterdam', 'Honduras', 'Klavier- und Cembalobauer'),
       ('Bergmann', 'Xaver', '44578', 'Rom', 'Lettland', 'Tischler'),
       ('Sommer', 'Yoshi', '36086', 'Berlin', 'Dominikanische Republik', 'Schirmmacher'),
       ('Krause', 'Brigitte', '22737', 'Amsterdam', 'Italien', 'Schreiner'),
       ('Winkler', 'Isa', '57553', 'Donezk', 'Laos', 'Holzbearbeitungsmechaniker'),
       ('Hofmann', 'Chris', '72448', 'Kasan', 'São Tomé und Príncipe', 'Zupfinstrumentenmacher'),
       ('Sauer', 'Patrick', '18524', 'Saragossa', 'Mauretanien', 'Holz- und Bautenschützer'),
       ('Walter', 'Donald', '65828', 'Bremen', 'Tonga', 'Drechsler'),
       ('Lehmann', 'Olaf', '38371', 'Balaschicha', 'Oman', 'Technischer Modellbauer'),
       ('Lang', 'Steffan', '85394', 'Neapel', 'Armenien', 'Zupfinstrumentenmacher'),
       ('Heinrich', 'Max', '58434', 'Krakau', 'Neuseeland', 'Bogenmacher'),
       ('Kraus', 'Tim', '63887', 'Lwiw', 'Slowenien', 'Klavier- und Cembalobauer'),
       ('Becker', 'Richard', '74230', 'Duisburg', 'Rumänien', 'Flechtwerkgestalter'),
       ('Dietrich', 'Günther', '84223', 'Barcelona', 'Brunei', 'Drechsler'),
       ('Simon', 'Olaf', '11033', 'Dublin', 'Botswana', 'Metallblasinstrumentenmacher'),
       ('Engel', 'Friedrich', '34979', 'München', 'Turkmenistan', 'Metallblasinstrumentenmacher'),
       ('Weiß', 'Olaf', '46756', 'Oslo', 'Dominikanische Republik', 'Bürsten- und Pinselmacher'),
       ('Kraus', 'Günther', '99525', 'Lipezk', 'Lesotho', 'Klavier- und Cembalobauer'),
       ('Wagner', 'Elsa', '79700', 'Mailand', 'Nordzypern', 'Holzspielzeugmacher'),
       ('Ludwig', 'Quentin', '59221', 'Lissabon', 'Mauritius', 'Schreiner'),
       ('Frank', 'Quentin', '83462', 'Leipzig', 'Tansania', 'Holz- und Bautenschützer'),
       ('Braun', 'Olaf', '33558', 'Dublin', 'Kroatien', 'Holzbearbeitungsmechaniker'),
       ('König', 'Chris', '95701', 'Amsterdam', 'Russland', 'Flechtwerkgestalter'),
       ('Walter', 'Steffan', '24651', 'Bradford', 'Philippinen', 'Technischer Modellbauer'),
       ('Sauer', 'Friedrich', '76914', 'Skopje', 'Simbabwe', 'Schreiner'),
       ('Marin', 'Ulf', '95613', 'Hannover', 'Katar', 'Geigenbauer'),
       ('Busch', 'Steffan', '64430', 'Lyon', 'Finnland', 'Holzmechaniker'),
       ('Richter', 'Patrick', '63587', 'Dresden', 'Portugal', 'Flechtwerkgestalter'),
       ('Friedrich', 'Tim', '30206', 'Moskau', 'Mosambik', 'Klavier- und Cembalobauer'),
       ('Hahn', 'Valentin', '62596', 'Rostow am Don', 'Polen', 'Leichtflugzeugbauer'),
       ('Berger', 'Patrick', '19040', 'Rjasan', 'Malawi', 'Biologiemodellmacher'),
       ('Zimmermann', 'Steffan', '93572', 'Lipezk', 'Kongo, Demokratische Republik', 'Schreiner'),
       ('Kühn', 'Patrick', '19962', 'Turin', 'Vereinigte Staaten', 'Schirmmacher'),
       ('Pohl', 'Friedrich', '93816', 'Nürnberg', 'Ungarn', 'Leichtflugzeugbauer'),
       ('Zimmermann', 'Luis', '22254', 'Göteborg', 'Albanien', 'Holz- und Bautenschützer'),
       ('Berger', 'Chris', '72511', 'Lissabon', 'Jamaika', 'Bootsbauer'),
       ('Ziegler', 'Friedrich', '93583', 'Hamburg', 'Griechenland', 'Spielzeughersteller'),
       ('Kühn', 'Steffan', '99720', 'Moskau', 'Venezuela', 'Schreiner'),
       ('Winter', 'Tim', '25219', 'Krakau', 'Libyen', 'Holzspielzeugmacher'),
       ('Neumann', 'Max', '21172', 'Chișinău', 'Israel', 'Technischer Modellbauer'),
       ('Scholz', 'Olaf', '43428', 'Kasan', 'Venezuela', 'Holzblasinstrumentenmacher'),
       ('Köhler', 'Albert', '71766', 'Krywyj Rih', 'Kolumbien', 'Holzbearbeitungsmechaniker'),
       ('Schäfer', 'Zoe', '81021', 'Krywyj Rih', 'Gambia', 'Klavier- und Cembalobauer'),
       ('Beck', 'Quentin', '18477', 'Wien', 'Tunesien', 'Geigenbauer'),
       ('Kraus', 'Isa', '80473', 'Posen', 'China, Volksrepublik', 'Spielzeughersteller'),
       ('Möller', 'Hans', '36436', 'Istanbul', 'Saudi-Arabien', 'Technischer Modellbauer'),
       ('Pohl', 'Wilhelm', '93572', 'Machatschkala', 'Moldau', 'Bürsten- und Pinselmacher'),
       ('Schulte', 'Wilhelm', '33328', 'Göteborg', 'Malawi', 'Technischer Modellbauer'),
       ('Hoffmann', 'Zoe', '55901', 'Lipezk', 'Russland', 'Schirmmacher'),
       ('Heinrich', 'Wilhelm', '74672', 'Nürnberg', 'Gambia', 'Holzmechaniker'),
       ('Schneider', 'Kirsten', '15989', 'Pensa', 'St. Vincent und die Grenadinen', 'Holzbildhauer'),
       ('Franke', 'Wilhelm', '26996', 'Helsinki', 'Nordzypern', 'Holzbildhauer'),
       ('Hartmann', 'Brigitte', '10405', 'Málaga', 'Peru', 'Fachkraft für Holz- und Bautenschutzarbeiten'),
       ('Hartmann', 'Olaf', '66180', 'Kirow', 'Dänemark', 'Zupfinstrumentenmacher'),
       ('Pohl', 'Quentin', '66427', 'Bradford', 'Estland', 'Leichtflugzeugbauer');

INSERT INTO PERSON_DATA_D (name, first_name, postcode, city, country, occupation)
VALUES ('Fuchs', 'Chris', '62970', 'Turin', 'Sudan', 'Holzmechaniker'),
       ('Albrecht', 'Norbert', '38655', 'Vilnius', 'Mali', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Vogel', 'Friedrich', '98539', 'Sevilla', 'Tunesien', 'Drechsler'),
       ('Günther', 'Luis', '62404', 'Rotterdam', 'Fidschi', 'Leichtflugzeugbauer'),
       ('Kaiser', 'Hans', '44292', 'Leeds', 'Georgien', 'Orgelbauer'),
       ('Pohl', 'Steffan', '58048', 'Krywyj Rih', 'Palau', 'Flechtwerkgestalter'),
       ('Richter', 'Max', '12996', 'Warschau', 'Libyen', 'Fachkraft für Holz- und Bautenschutzarbeiten'),
       ('Frank', 'Olaf', '48921', 'Woronesch', 'Albanien', 'Leichtflugzeugbauer'),
       ('Böhm', 'Albert', '51428', 'Leipzig', 'Kuba', 'Holzmechaniker'),
       ('Böhm', 'Tim', '94958', 'Bremen', 'Seychellen', 'Orgelbauer'),
       ('Fischer', 'Steffan', '25169', 'Lwiw', 'Gambia', 'Tischler'),
       ('Lorenz', 'Norbert', '65870', 'Machatschkala', 'Guinea-Bissau', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Fuchs', 'Yoshi', '86255', 'Saratow', 'Estland', 'Holzbildhauer'),
       ('Mayer', 'Yoshi', '73751', 'Helsinki', 'Kamerun', 'Orgelbauer'),
       ('Müller', 'Xaver', '54999', 'Marseille', 'Sudan', 'Bootsbauer'),
       ('Zimmermann', 'Ulf', '66079', 'Sheffield', 'Niger', 'Böttcher'),
       ('Roth', 'Kirsten', '15906', 'Leipzig', 'Salomonen', 'Holzbearbeitungsmechaniker'),
       ('Kraus', 'Ulf', '75199', 'Amsterdam', 'Östereich', 'Klavier- und Cembalobauer'),
       ('Mayer', 'Kirsten', '89830', 'Riga', 'Gabun', 'Technischer Modellbauer'),
       ('Keller', 'Brigitte', '46160', 'Palermo', 'Frankreich', 'Biologiemodellmacher'),
       ('Schulze', 'Kirsten', '78475', 'Glasgow', 'Irland', 'Bürsten- und Pinselmacher'),
       ('Hahn', 'Albert', '46354', 'Toljatti', 'Algerien', 'Geigenbauer'),
       ('Dietrich', 'Isa', '62185', 'Kiew', 'Malaysia', 'Zupfinstrumentenmacher'),
       ('Huber', 'Tim', '18788', 'Barcelona', 'Nicaragua', 'Orgelbauer'),
       ('Pohl', 'Ulf', '78377', 'Bukarest', 'Cookinseln', 'Schirmmacher'),
       ('Bauer', 'Ulf', '80710', 'Ufa', 'Libyen', 'Zupfinstrumentenmacher'),
       ('Keller', 'Steffan', '44815', 'Chișinău', 'Suriname', 'Biologiemodellmacher'),
       ('Horn', 'Tim', '46699', 'Krasnodar', 'Tschechien', 'Biologiemodellmacher'),
       ('Krause', 'Chris', '88324', 'Genua', 'Gabun', 'Leichtflugzeugbauer'),
       ('Thomas', 'Wilhelm', '61321', 'Zagreb', 'Paraguay', 'Holzspielzeugmacher'),
       ('Schmid', 'Tim', '96469', 'Essen', 'Irak', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Fischer', 'Norbert', '92800', 'Odessa', 'Peru', 'Drechsler'),
       ('Herrmann', 'Brigitte', '37703', 'München', 'Dominikanische Republik', 'Zupfinstrumentenmacher'),
       ('Neumann', 'Hans', '73508', 'Ischewsk', 'Kolumbien', 'Klavier- und Cembalobauer'),
       ('Schmitz', 'Yoshi', '21358', 'London', 'Kenia', 'Schreiner'),
       ('Neumann', 'Olaf', '18170', 'Krywyj Rih', 'Syrien', 'Holzmechaniker'),
       ('Seidel', 'Justin', '57367', 'Perm', 'Libyen', 'Bogenmacher'),
       ('Ziegler', 'Wilhelm', '79028', 'London', 'Tansania', 'Drechsler'),
       ('Albrecht', 'Günther', '77460', 'Rom', 'Lesotho', 'Tischler'),
       ('Thomas', 'Friedrich', '87668', 'Oslo', 'Kamerun', 'Böttcher'),
       ('Neumann', 'Steffan', '32632', 'Łódź', 'Gambia', 'Bürsten- und Pinselmacher'),
       ('Herrmann', 'Justin', '45354', 'Neapel', 'Honduras', 'Biologiemodellmacher'),
       ('Schulte', 'Elsa', '74463', 'Málaga', 'Burkina Faso', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Brandt', 'Steffan', '45987', 'Leipzig', 'Turkmenistan', 'Schirmmacher'),
       ('Horn', 'Günther', '49044', 'Riga', 'Ruanda', 'Metallblasinstrumentenmacher'),
       ('Voigt', 'Ulf', '27044', 'München', 'St. Vincent und die Grenadinen', 'Metallblasinstrumentenmacher'),
       ('Schulz', 'Tim', '90152', 'Lwiw', 'Belgien', 'Biologiemodellmacher'),
       ('Fuchs', 'Steffan', '88716', 'Sofia', 'Kap Verde', 'Holzmechaniker'),
       ('Haas', 'Chris', '74386', 'Dortmund', 'Niue', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Busch', 'Isa', '65906', 'Wolgograd', 'Elfenbeinküste', 'Leichtflugzeugbauer'),
       ('Peters', 'Richard', '17946', 'Leipzig', 'Dominikanische Republik', 'Bootsbauer'),
       ('Lehmann', 'Norbert', '74972', 'Homel', 'El Salvador', 'Tischler'),
       ('Fuchs', 'Chris', '90053', 'Barcelona', 'Australien', 'Fachkraft für Holz- und Bautenschutzarbeiten'),
       ('Fischer', 'Max', '83007', 'Woronesch', 'Südossetien', 'Flechtwerkgestalter'),
       ('Lorenz', 'Isa', '73311', 'Frankfurt am Main', 'Saudi-Arabien', 'Holzmechaniker'),
       ('Marin', 'Friedrich', '24820', 'Istanbul', 'Malaysia', 'Metallblasinstrumentenmacher'),
       ('Klein', 'Tim', '21223', 'Tirana', 'Frankreich', 'Klavier- und Cembalobauer'),
       ('Winkler', 'Steffan', '68045', 'München', 'Papua-Neuguinea', 'Leichtflugzeugbauer'),
       ('Vogt', 'Albert', '31003', 'Antwerpen', 'Malaysia', 'Zupfinstrumentenmacher'),
       ('Heinrich', 'Justin', '78991', 'Saporischschja', 'Guyana', 'Böttcher'),
       ('Hofmann', 'Chris', '69005', 'Woronesch', 'Bahamas', 'Leichtflugzeugbauer'),
       ('Lehmann', 'Steffan', '73733', 'Antwerpen', 'Bolivien', 'Schreiner'),
       ('Schreiber', 'Yoshi', '47780', 'Lipezk', 'Portugal', 'Holzbildhauer'),
       ('Richter', 'Ulf', '74863', 'Sofia', 'Niederlande', 'Holzmechaniker'),
       ('Ludwig', 'Günther', '11754', 'Rom', 'Korea, Süd', 'Klavier- und Cembalobauer'),
       ('Wagner', 'Max', '67039', 'Berlin', 'Bahrain', 'Fachkraft für Holz- und Bautenschutzarbeiten'),
       ('Seidel', 'Isa', '36271', 'Lissabon', 'Katar', 'Holzbildhauer'),
       ('Schmidt', 'Hans', '59706', 'Düsseldorf', 'Usbekistan', 'Holzbearbeitungsmechaniker'),
       ('Schmitt', 'Albert', '85690', 'Birmingham', 'Malaysia', 'Orgelbauer'),
       ('Seidel', 'Justin', '13806', 'Breslau', 'Burundi', 'Bootsbauer'),
       ('Frank', 'Tim', '96639', 'Göteborg', 'China, Volksrepublik', 'Bootsbauer'),
       ('Becker', 'Patrick', '18049', 'Nabereschnyje Tschelny', 'Bhutan', 'Bogenmacher'),
       ('Schröder', 'Albert', '20802', 'Rotterdam', 'St. Kitts und Nevis',
        'Fachkraft für Holz- und Bautenschutzarbeiten'),
       ('Simon', 'Tim', '87326', 'Krakau', 'Guinea', 'Handzuginstrumentenmacher'),
       ('Lehmann', 'Albert', '56452', 'Wien', 'Malawi', 'Holzspielzeugmacher'),
       ('Pohl', 'Tim', '50386', 'Neapel', 'Syrien', 'Bogenmacher'),
       ('Ziegler', 'Steffan', '95678', 'Valencia', 'Madagaskar', 'Drechsler'),
       ('Fuchs', 'Richard', '20734', 'Kirow', 'Griechenland', 'Orgelbauer'),
       ('Beck', 'Kirsten', '27771', 'Skopje', 'Slowenien', 'Schreiner'),
       ('Horn', 'Brigitte', '45772', 'Nabereschnyje Tschelny', 'São Tomé und Príncipe', 'Biologiemodellmacher'),
       ('Friedrich', 'Max', '89551', 'Moskau', 'Korea, Süd', 'Klavier- und Cembalobauer'),
       ('Heinrich', 'Günther', '63056', 'Lipezk', 'Katar', 'Handzuginstrumentenmacher'),
       ('Haas', 'Yoshi', '80727', 'London', 'Elfenbeinküste', 'Holzbearbeitungsmechaniker'),
       ('Busch', 'Chris', '98725', 'Manchester', 'Grenada', 'Handzuginstrumentenmacher'),
       ('Busch', 'Norbert', '48748', 'Athen', 'Portugal', 'Holzbildhauer'),
       ('Hahn', 'Donald', '26377', 'München', 'Ungarn', 'Zupfinstrumentenmacher'),
       ('Schreiber', 'Richard', '83044', 'Lwiw', 'Libanon', 'Klavier- und Cembalobauer'),
       ('Lehmann', 'Max', '18013', 'Homel', 'Norwegen', 'Handzuginstrumentenmacher'),
       ('Köhler', 'Albert', '69316', 'Neapel', 'Aserbaidschan', 'Klavier- und Cembalobauer'),
       ('Bauer', 'Isa', '55990', 'Rom', 'Panama', 'Böttcher'),
       ('Bergmann', 'Quentin', '76391', 'Ischewsk', 'Tschechien', 'Schirmmacher'),
       ('Simon', 'Yoshi', '88670', 'Frankfurt am Main', 'Niue', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Friedrich', 'Justin', '82172', 'Ufa', 'Ungarn', 'Technischer Modellbauer'),
       ('Meyer', 'Luis', '50185', 'Zagreb', 'Nigeria', 'Geigenbauer'),
       ('Schulte', 'Olaf', '53114', 'Marseille', 'Schweden', 'Holzblasinstrumentenmacher'),
       ('Schumacher', 'Elsa', '51048', 'Düsseldorf', 'Senegal', 'Geigenbauer'),
       ('Weiß', 'Isa', '99552', 'Breslau', 'Australien', 'Klavier- und Cembalobauer'),
       ('Mayer', 'Brigitte', '41566', 'Leipzig', 'Südsudan', 'Holzbearbeitungsmechaniker'),
       ('Schmitt', 'Zoe', '73790', 'Łódź', 'Afghanistan', 'Rollladen- und Sonnenschutzmechatroniker'),
       ('Lehmann', 'Luis', '90652', 'London', 'Bangladesch', 'Metallblasinstrumentenmacher'),
       ('Meyer', 'Donald', '68874', 'Wien', 'Guatemala', 'Bogenmacher');

COMMIT;